---
title: 在使用Git提交代码的时候犯了个低级错误
date:  2018年3月29日
tags:  git,总结
categories: 前端
---


今天在使用git提交代码的时候，犯了个很低级的错误，按照一切流程当我add并commit提交代码，最后使用push到远程仓库，

接下来奇怪的事情发生了，push之后，查看远程仓库代码并没有发现提交记录，emmmm~  

此时我内心是不淡定的，什么他妈的鬼？我提交的代码去哪里了 ？

正好此时，赶上运维升级服务器，以为是服务器的问题，等服务器升级完再试一试。

MD，服务器升级完了，再次push在远程仓库仍然无法看到提交记录，在本地使用git -log查看提交记录，

草，这不是有提交记录吗，真是见了鬼了哦！

![](https://images2018.cnblogs.com/blog/871647/201803/871647-20180329230628539-1173376986.png)

没办法，叫同事过来帮看一下，再次push仍然提示没有需要push的内容，那既然这样，我把本地的代码随便

修改个地方，提交并push上去看看可不可以，发现问题了，卧槽。原来是在push代码的时候rejected被拒绝了，emmmm...

![](https://images2018.cnblogs.com/blog/871647/201803/871647-20180329230105397-1900330801.png)

上面的提示已经很明显了，大致意思是说当前分支落后于远程分支，在push代码之前先pull一下  ， 但是我想想~

我记得，在我push之前我一般都pull过了啊 ， 然后问了下同事才知道，原来在git pull默认是不知道你要pull哪个远程分支，

所以像这样git pull origin data_center_update  后面指定pull的远程分支，问题解决 。

最后，总结一下
 
真的是犯了个很低级的错误，其实没有必要单独写个博客，但我觉得，以后这样的问题不能再出现了，所以想给自己提个醒，

在博客中记录下来，以后出现这样的问题，要细心细心再细心。



>作者：fozero
>声明：原创文章，转载请注明出处，谢谢！[http://www.cnblogs.com/fozero/p/8673298.html](http://www.cnblogs.com/fozero/p/8673298.html)                      
>标签：总结，git